### ISSUE TITLE
Wrong dependency in pom.xml

### ISSUE THREAD

**Issue by joakimb** [peteroupc/CBOR-Java#1]
Thanks for a great project!
When using maven to build, the reference to numbers should have version number  <version>0.2.0</version> instead of <version>0.2.0-SNAPSHOT</version>

**Comment by peteroupc** [comment]
Thanks for reporting.
I have fixed certain bugs in version 0.2 of numbers in the meantime, so it may change to 0.2.1 in the near future.  I will let you know when it's ready.

**Comment by peteroupc** [comment]
I've released a new version 2.4.1 on the Central Repository.  Hopefully this fixes this issue.
