### ISSUE TITLE
Object Mapper

### ISSUE THREAD

**Issue by webfolderio** [peteroupc/CBOR-Java#11]
Hi,

Is there a way to convert Java Object to CBOR without manual mapping.

eg.:
CBorObject object = ObjectMapper.toCBor(new Person());

**Comment by peteroupc** [comment]
The `CBORObject.FromObject` method already supports converting custom types of objects to CBOR.  See the Javadoc for `CBORObject.FromObject` for more information.  Generally, this means that your `Person` class should consist only of public fields, or public methods starting with `get`.
