### ISSUE TITLE
Control field order at serialization

### ISSUE THREAD

**Issue by sbernard31** [peteroupc/CBOR-Java#13]
Currently, fields in CBOR object are not serialized by insertion order.
Reading the code, I suspect there is no way to do that.

I suppose if I was able to create a CBOR map with a LinkedHashMap, insertion order could be kept ?
```java
    /**
     * Creates a new empty CBOR map.
     * @return A new CBOR map.
     */
    public static CBORObject NewMap() {
      return new CBORObject(
        CBORObjectTypeMap,
        new LinkedHashMap<CBORObject, CBORObject>());
    }
```

**Comment by peteroupc** [comment]
There is no explicit support in this library for writing maps to CBOR in insertion order.  However, the documentation includes example code that shows how to write such maps in a given order.  See

https://peteroupc.github.io/CBOR/docs/PeterO.Cbor.CBORObject.html#WriteTo_System_IO_Stream

Note that the examples are in C#, not Java (since the Java version "borrows" the code from the C# version, in a sense), but they should be simple to adapt to Java.

Alternatively, try the CTAP2 canonicalization, which imposes a specific map key order, among other things, especially if you're dealing with WebAuthn and CBOR:

`cbor.EncodeToBytes(new CBOREncodeOptions("ctap2canonical=true"))`

Try any of these and see whether they work for you.

**Comment by sbernard31** [comment]
@peteroupc, thx for the answer.

I tried `cbor.EncodeToBytes(new CBOREncodeOptions("ctap2canonical=true"))` without so many hope.
This changes the order but still not the insertion one. (as expected)

About https://peteroupc.github.io/CBOR/docs/PeterO.Cbor.CBORObject.html#WriteTo_System_IO_Stream 
I looked at this but this sounds pretty much too low level code. I have a complex structure with array and map. This will make the code much less readable and more error prone. 

If I used java reflection API to access to hidden `CBORObject` constructor and create an instance with a `LinkedHashMap` instead of `HashMap`, this works as I expected. (insert order is respected)

I mean using this : 
```java
// create CBORObject with LinkedHashMap
Constructor<CBORObject> constructor = CBORObject.class.getDeclaredConstructor(int.class, Object.class);
constructor.setAccessible(true);
CBORObject cborMap = constructor.newInstance(5, new LinkedHashMap<CBORObject, CBORObject>());
```
instead of : 
```java
CBORObject cborMap = CBORObject.NewMap()
```

Of course using reflection is not elegant at all and it would be better to provide a dedicated API which allows : 
```java
CBORObject cborMap = CBORObject.NewMap(new LinkedHashMap<CBORObject, CBORObject>())
// or 
boolean keepInsertionOrder = true
CBORObject cborMap = CBORObject.NewMap(keepInsertionOrder) // which use a linkedHashMap internally
```

**Comment by sbernard31** [comment]
@peteroupc  do you think adding this kind of API :point_up:  could make sense ?

About the other solution using `CBORObject.WriteValue(outputStream, ...)` API.
An idea, maybe adding : 
 - WriteStartMap(size);
 - WriteStartMap();
 - WriteEndMap();
 - WriteStartArray(size);
 - WriteStartArray();
 - WriteEndArray()

 could be helpful ?

**Comment by peteroupc** [comment]
I have just added a `CBORObject.NewOrderedMap()` method.

**Comment by sbernard31** [comment]
> I have just added a CBORObject.NewOrderedMap() method.

Good to know !

> Also, on your suggestion on new methods for writing objects: I suggest creating a new helper class with a "fluent" API, rather than adding more methods to the CBORObject class, which is already very big

Probably better, I agree :+1: 

> Finally, I have extended FromObject and ToObject to support serializing and deserializing BigDecimal and BigInteger.

Great ! :tada: 

Do you have any approximate version and release date for all of this feature ?

**Comment by sbernard31** [comment]
Should we close this issue and I create a dedicated one for "fluent API" or we just keep this one open ?

**Comment by peteroupc** [comment]
> Should we close this issue and I create a dedicated one for "date API improvement" or we just keep this one open ?

I just wrote the following, which implements the kind of "fluent" API I had in mind:

https://github.com/peteroupc/CBOR-Java/blob/master/src/test/java/com/upokecenter/test/CBORWriterHelper.java

**Comment by sbernard31** [comment]
> In any case, I expect to release version 4.3 either today or very soon.

:tada: !

> I just wrote the following, which implements the kind of "fluent" API I had in mind:

I just looked at it. It sounds good. :+1: 

Maybe we could imagine some checks :
 - do not end a map or an array which don't need end. (because size is known)  (instead of check we can also just don't write the end byte if not needed)
 - not too many or not enough field.
 - use `Write(Object value)` for array only
 - use ` Write(Object key, Object value)` for Map only.

But this means adding internal state in your helper.

**Comment by peteroupc** [comment]
Version 4.3 was just released.

**Comment by sbernard31** [comment]
I just integrated it and that sounds to work like charm.

@peteroupc thx for your time :pray: !
