### ISSUE TITLE
Question : how to encode an unsigned long from a long ?

### ISSUE THREAD

**Issue by sbernard31** [peteroupc/CBOR-Java#15]
The question sounds a bit silly but in Java, there is a common usage to store an unsigned long in a long (new API was added since Java 8) : 
 - parseUnsignedLong(String s)
 - toUnsignedString(long i)
 (and all other unsigned methods : https://docs.oracle.com/javase/8/docs/api/java/lang/Long.html)

My question is : In case I store an unsigned long in a long in java. What could be the right way to encode it in CBOR using CBOR-java ?

I know I can do something like : 
```java
CBORObject.FromObject(EInteger.FromString(Long.toUnsignedString(myLong)));
```
But I guess there is a smarter way without using a String.

(I hope my question is clear, I'm no so sure :sweat_smile:)

**Comment by peteroupc** [comment]
You can use `FromObject` as well as an `EInteger` or `BigInteger` generated using either `fromUnsignedLong` method below.  I've just written them now and didn't test them yet.

```
public static EInteger fromUnsignedLong(long v) {
  if (v >= 0) {
     return EInteger.FromInt64(v);
  } else {
     return EInteger.FromInt32(1).ShiftLeft(64).Add(v);
  }
}

public static BigInteger fromUnsignedLong(long v) {
  if (v >= 0) {
     return BigInteger.valueOf(v);
  } else {
     return BigInteger.valueOf(1).shiftLeft(64).add(
          BigInteger.valueOf(v));
  }
}
```

**Comment by sbernard31** [comment]
I tested it quickly and it seems to work. Is it something which makes sense to add in CBOR-Java ?
 
Another question about this usage of `long` to store unsigned long.
If now I want to serialize an unsigned long like this and I want to be sure the integer fit in a unsigned long, is it OK to check like this ?  
```java
CBORNumber number = cborObject.AsNumber();
if (number.IsInteger()
    && !number.IsNegative() 
    && number.ToEIntegerIfExact().GetUnsignedBitLengthAsInt64() <= 64) {
    return number.ToInt64Unchecked();
}
```

About `GetUnsignedBitLengthAsInt64`, I'm not sure to get the difference with `GetSignedBitLengthAsInt64` :thinking: (probably because my number encoding level is too low :grin:)
About those methods, I suspect there is an issue in the javadoc in **@return** part (both methods):
> Returns:
The number of bits ... ...,  Returns 0 if this object's value is 0, and returns 1 if the value is negative 1. Returns 2^63 - 1 (Long.MAX_VALUE in.NET or Long.MAX_VALUE in Java) if the number of bits is 2^63 - 1 or greater.

**Comment by peteroupc** [comment]
> I tested it quickly and it seems to work. Is it something which makes sense to add in CBOR-Java ?
> 
> Another question about this usage of `long` to store unsigned long.
> If now I want to serialize an unsigned long like this and I want to be sure the integer fit in a unsigned long, is it OK to check like this ?
> 
> ```java
> CBORNumber number = cborObject.AsNumber();
> if (number.IsInteger()
>     && !number.IsNegative() 
>     && number.ToEIntegerIfExact().GetUnsignedBitLengthAsInt64() <= 64) {
>     return number.ToInt64Unchecked();
> }
> ```

That is correct as far as I can tell.

> 
> About `GetUnsignedBitLengthAsInt64`, I'm not sure to get the difference with `GetSignedBitLengthAsInt64` thinking (probably because my number encoding level is too low grin)
> About those methods, I suspect there is an issue in the javadoc in **@return** part (both methods):
> 
> > Returns:
> > The number of bits ... ...,  Returns 0 if this object's value is 0, and returns 1 if the value is negative 1. Returns 2^63 - 1 (Long.MAX_VALUE in.NET or Long.MAX_VALUE in Java) if the number of bits is 2^63 - 1 or greater.

I don't see the issue here.

**Comment by sbernard31** [comment]
My mistake :facepalm:... I read to quickly:  
> Returns 2^63 - 1 (Long.MAX_VALUE in.NET or Long.MAX_VALUE in Java) if the number ~of bits~ is 2^63 - 1 or greater.

About my test above, we could maybe add something like : `CanFitInUnsignedInt64` ?

**Comment by peteroupc** [comment]
> My mistake facepalm... I read to quickly:
> 
> > Returns 2^63 - 1 (Long.MAX_VALUE in.NET or Long.MAX_VALUE in Java) if the number ~of bits~ is 2^63 - 1 or greater.

In fact, that's not how it should be read.  Rather, it should be read as: "If the return value would be greater than 2^63 - 1 (Long.MAX_VALUE in Java), returns 2^63 - 1 instead."

> 
> About my test above, we could maybe add something like : `CanFitInUnsignedInt64` ?

No, because I don't believe it will be required very often.

**Comment by sbernard31** [comment]
> In fact, that's not how it should be read. Rather, it should be read as: "If the return value would be greater than 2^63 - 1 (Long.MAX_VALUE in Java), returns 2^63 - 1 instead."

Yep I get it finally.

> No, because I don't believe it will be required very often.

Ok, no problem :)
(I feel this is maybe not so true because in java since new unsigned API was added is pretty common to use a long to store an unsigned long, anyway If you feel this is not needed)

Thx again for your time :pray:
