### ISSUE TITLE
Many classes are package private

### ISSUE THREAD

**Issue by martin-lindstrom** [peteroupc/CBOR-Java#16]
Many of the classes that I would like to access is package private, for example CBORUtilities, PropertyMap. Is there a reason that you don't expose all of your classes?

**Comment by peteroupc** [comment]
CBORUtilities and PropertyMap include helper methods used to implement the CBOR library.  They are not documented as part of the public API, and the same is true for all other "package-private" classes in this library.

**Comment by martin-lindstrom** [comment]
Yes. I understand. But it is a pity since you have some valuable code for us that are using your (excellent) library to implement CWT:s according to RFC 8392. 
I ran into problems concerning the `CBORDateConverter` where CWT states that no outer tag should be used. 

p.s. I think that you'll get a lot new users since the EU has suggested using CBOR/CWT/COSE for the green vaccination passes.

**Comment by peteroupc** [comment]
Yes, this is a problem if you're using `Date`s to serialize and deserialize CBOR objects, due to section 5 of that RFC.  However, the date conversion utilities are quite low level, so that it wouldn't make sense to expose them in the API of a library devoted to CBOR.

**Comment by peteroupc** [comment]
I have made the CBORDateConverter class public and expanded its functionality.

**Comment by martin-lindstrom** [comment]
Excellent! Much appreciated.

**Comment by peteroupc** [comment]
Apparently resolved.
