### ISSUE TITLE
Mis-match between this source and Maven

### ISSUE THREAD

**Issue by jimsch** [peteroupc/CBOR-Java#2]
I just got a bug that getOutermostTag has been deprecated in this project.  I see from the sources that it is, however it does not appear to be in the latest release of 2.4.1 on Maven.  Is it meant to be?

**Comment by peteroupc** [comment]
It will be deprecated in version 3.0.0 of my library; the source code in the master branch contains a development snapshot of that version, not the final version (see pom.xml).

**Comment by jimsch** [comment]
Great I thought that might be the case, but could not tell based on the latest commit dates.
