### ISSUE TITLE
NullPointerException("value") for key == null

### ISSUE THREAD

**Issue by boaks** [peteroupc/CBOR-Java#21]
Let me say "thank you, for this great library!" 

Viewing the sources I found a small code smell:

[CBORObject.set](https://github.com/peteroupc/CBOR-Java/blob/master/src/main/java/com/upokecenter/cbor/CBORObject.java#L721-L727)

```
if (key == null) {
      throw new NullPointerException("value");
}
```

In my opinion, this should be `"key"`.

The same is true, for the other flavor a few lines below that.

**Comment by peteroupc** [comment]
Fixed.
