### ISSUE TITLE
CBORObject.NewOrderedMap() counterpart when reading from bytes?

### ISSUE THREAD

**Issue by boaks** [peteroupc/CBOR-Java#22]
Sometimes, mainly for "easy display usage", the order of a map is also useful.

Creating CBOR objects, this could be achieved by using `CBORObject.NewOrderedMap()`.
Is it possible, to achieve that also when reading the CBOR object from bytes?

**Comment by boaks** [comment]
Maybe a flag, to switch to `CBORObject.NewOrderedMap()` by default when reading?

**Comment by peteroupc** [comment]
That is what I had in mind already -- an option to preserve key order when decoding a CBOR object from bytes.

**Comment by peteroupc** [comment]
Implemented.

**Comment by boaks** [comment]
Great! Works for me ;-).
