### ISSUE TITLE
cbor 4.5 - supported java version?

### ISSUE THREAD

**Issue by boaks** [peteroupc/CBOR-Java#23]
Has the target java version for the 4.5 release changed from 1.7 to 1.8?

**Comment by peteroupc** [comment]
The target Java version was changed to 8 from 6 because Maven no longer supports compiling for Java version 6.

**Comment by boaks** [comment]
Thanks! java 7 is no option? 
(It's not a that big thing, but for now, I still try to support java 7 :-). )

**Comment by boaks** [comment]
(And just to say: thanks for the 4.5 release with the sorted map option!)

**Comment by peteroupc** [comment]
Maven still supports compiling for Java version 7; I may consider changing the target version to that in a later version of this library.

**Comment by boaks** [comment]
That would be great!

**Comment by peteroupc** [comment]
Addressed in version 4.5.2 (and 4.5.1).

**Comment by boaks** [comment]
Cool, I will pick it in the afternoon.
