### ISSUE TITLE
Publish signing key fingerprint

### ISSUE THREAD

**Issue by philsmart** [peteroupc/CBOR-Java#26]
Hello

Do you publish the fingerprints of your signing keys somewhere?

We [1] need to be able to do independent verification that the certificate and key we're verifying against for cbor 4.5.2 from Maven Central [2] is indeed the one you intend so that we don't find ourselves incorrectly verifying against a key that isn't yours. It was signed using RSA key 1A82 D514 0700 3717 A417  1AAC 8752 2D61 8F2B 2338.

[1] https://shibboleth.atlassian.net/wiki/spaces/DEV/pages/3269918721/Supply+Chain+Defence+for+the+Shibboleth+Java+Products
[2] https://mvnrepository.com/artifact/com.upokecenter/cbor/4.5.2

**Comment by peteroupc** [comment]
I just noticed that you posted your issue in the .NET version of the library rather than the Java version, so I have transferred it to the correct repository, but I have now mentioned the signing key for the Java version:

- https://github.com/peteroupc/cbor-java

I now consider it done.

**Comment by philsmart** [comment]
Ah, sorry. Thanks!
