### ISSUE TITLE
Version 4.5.3 pulls in the class DataUtilities twice

### ISSUE THREAD

**Issue by markuskreusch** [peteroupc/CBOR-Java#27]
After updating to 4.5.3 the class DataUtilities is added twice. One time in this library and one time in the transitive dependency com.github.peteroupc:datautilties:1.1.0. This causes problems in android builds. Are the two classes identical? In this case the class in this library should be deleted in favor of the version through the dependency.

**Comment by peteroupc** [comment]
Solved by releasing version 4.5.4, using the `datautilities` dependency.
