### ISSUE TITLE
Compatibility with c-rack library(https://github.com/c-rack/cbor-java)

### ISSUE THREAD

**Issue by jas-singh14** [peteroupc/CBOR-Java#4]
We have a situation where client has to use peteroupc CBOR library whereas server has to use c-rack CBOR library(https://github.com/c-rack/cbor-java)
Although both comply to RFC 7049. but wanted to doubly sure if there are any potential challenges/issues w.r.t to the above mentioned arrangement.

**Comment by peteroupc** [comment]
If you are concerned about interoperability, you should test how both implementations encode and decode CBOR, switching the implementations on the client and server side if possible.  If you see any interop issues, you should post here and include minimal sample CBOR files showing the problems, if possible.

**Comment by jas-singh14** [comment]
I would have loved to do that. However, I really don't have sufficient time for that as we need to close the decision ASAP. 
So, my request was that based on your past experience/expertise, do you foresee any compatibility issues?

**Comment by peteroupc** [comment]
The biggest, if not the only, possible issue that I see is that my implementation doesn't guarantee map keys are sorted when it writes out CBOR maps.  This is generally not an issue unless a protocol or specification cares about the order in which entries are written in a CBOR map.

**Comment by jas-singh14** [comment]
Thanks for the information. 
how can we find and eliminate such incompatibility issues? Due to time constraint, it won't be possible to do the full compatibility tesing/

**Comment by jas-singh14** [comment]
I checked and there is no need to transfer maps over the wire. Most of the data transferred is arrays (where each array element is string, integer or float).
Considering this, there shouldn't be any issue. Right?

**Comment by peteroupc** [comment]
I don't see any big issues with that, then.

**Comment by peteroupc** [comment]
Closing this issue.
