### ISSUE TITLE
Escaping of special characters while serialization and de-serialization

### ISSUE THREAD

**Issue by jas-singh14** [peteroupc/CBOR-Java#5]
How special characters in JSON strings are handled by peteroupc library while serialization and de-serialization?
Also is the behaviour same for all the CBOR libraries that conform to RFC 7049?
Please clarify

**Comment by jas-singh14** [comment]
Do you foresee any challenges due to this? e.g. in case client is using one Json<->CBOR library and server is using another JSON<->CBOR library? can there be a potential issue (related with handling of special escaped characters) while serialization/de-serialization?

**Comment by peteroupc** [comment]
I'm sorry, the issues list is not a place for such theoretical questions as that.  I would rather see a question where you have come across an _actual_ situation where my library doesn't has _actual_ interoperability problems with other libraries or the application, or a situation where you have come across an _actual_ bug with my library.  See also the comment by @c-rack on [one of your previous issues](https://github.com/c-rack/cbor-java/issues/66).

I am closing this issue.
